### ISSUE TITLE
User provider driver

### ISSUE THREAD

**Issue by cyberfly** [jotaelesalinas/laravel-simple-ldap-auth#8]
Hi, 

On Step 3, we need to change the user provider driver to aldap instead of eloquent. This works, however normal user authentication will break. 

Is there any alternative where I can dynamically set the user provider driver so I can choose which user to user normal auth and which user to ldap auth?

Thanks

**Comment by jotaelesalinas** [comment]
I think you should use [Adldap2/Adldap2-Laravel](https://github.com/Adldap2/Adldap2-Laravel) for that. It was meant to use LDAP authentication instead of local DB.

If you want a mixed system, you have to either give the end user the possibility of choosing which system to authenticate with or either use one first and the other as a fallback. You will have to modify the logic in `app/Http/Controllers/Auth/LoginController.php`.

**Comment by jotaelesalinas** [comment]
Sorry but this issue goes beyond my knowledge of Laravel. Closing.
